version: "3.9"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: stdpsw
      MYSQL_DATABASE: counter
      MYSQL_USER: user
      MYSQL_PASSWORD: stdpsw
